//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration_OperationalEventDetail
    {
        public long OperationalEventDetailId { get; set; }
        public long OperationalEventId { get; set; }
        public long OperationTypeId { get; set; }
        public Nullable<long> PaymentModeId { get; set; }
        public string Prefix { get; set; }
        public string NumberFormat { get; set; }
        public string AdditionOrDeduction { get; set; }
        public bool Voucher { get; set; }
        public Nullable<long> VoucherConfigurationId { get; set; }
        public Nullable<long> DefaultPriceTypeId { get; set; }
        public Nullable<long> DefaultCustomerId { get; set; }
        public Nullable<long> DefaultPaymentModeId { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
    
        public virtual Configuration_OperationalEvent Configuration_OperationalEvent { get; set; }
        public virtual Configuration_OperationType Configuration_OperationType { get; set; }
        public virtual Configuration_PaymentMode Configuration_PaymentMode { get; set; }
        public virtual Configuration_PaymentMode Configuration_PaymentMode1 { get; set; }
        public virtual Configuration_Voucher Configuration_Voucher { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Customer Setup_Customer { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_PriceType Setup_PriceType { get; set; }
    }
}
