//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration_Features
    {
        public long Id { get; set; }
        public long FeatureId { get; set; }
        public Nullable<long> SubFeatureId { get; set; }
        public bool Value { get; set; }
        public Nullable<long> OperationEventId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Features Setup_Features { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_SubFeatures Setup_SubFeatures { get; set; }
    }
}
