//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Others_Documents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Others_Documents()
        {
            this.Task_ImportDocuments = new HashSet<Task_ImportDocuments>();
        }
    
        public System.Guid DocumentId { get; set; }
        public string DocumentNo { get; set; }
        public long OperationalEventId { get; set; }
        public string OperationNo { get; set; }
        public long TitleId { get; set; }
        public string Description { get; set; }
        public byte[] FileRecord { get; set; }
        public string FileType { get; set; }
        public string DocumentName { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Configuration_OperationalEvent Configuration_OperationalEvent { get; set; }
        public virtual Security_User Security_User { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_DocumentsTitle Setup_DocumentsTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ImportDocuments> Task_ImportDocuments { get; set; }
    }
}
