//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Others_ReportDesignConfig
    {
        public long ReportDesignId { get; set; }
        public long OperationalEventId { get; set; }
        public bool ShowHeader { get; set; }
        public long HeaderHeight { get; set; }
        public bool ShowLocationAddress { get; set; }
        public string DefaultReportName { get; set; }
        public long PaperLength { get; set; }
        public long PaperWidth { get; set; }
        public long LeftMargin { get; set; }
        public long CompanyId { get; set; }
    
        public virtual Configuration_OperationalEvent Configuration_OperationalEvent { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
    }
}
