//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security_UserLocation
    {
        public long SecurityUserLocationId { get; set; }
        public long SecurityUserId { get; set; }
        public long LocationId { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
    }
}
