//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Security_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Security_User()
        {
            this.Configuration_CurrencyRate = new HashSet<Configuration_CurrencyRate>();
            this.Configuration_EventWiseCharge = new HashSet<Configuration_EventWiseCharge>();
            this.Configuration_Features = new HashSet<Configuration_Features>();
            this.Configuration_GovtDutyRate_HSCode = new HashSet<Configuration_GovtDutyRate_HSCode>();
            this.Configuration_GovtDutyRate_Location = new HashSet<Configuration_GovtDutyRate_Location>();
            this.Others_Documents = new HashSet<Others_Documents>();
            this.Security_RoleWiseMenuPermission = new HashSet<Security_RoleWiseMenuPermission>();
            this.Security_UserLocation = new HashSet<Security_UserLocation>();
            this.Security_UserWiseMenuPermission = new HashSet<Security_UserWiseMenuPermission>();
            this.Security_UserWiseMenuPermission1 = new HashSet<Security_UserWiseMenuPermission>();
            this.Setup_Accounts = new HashSet<Setup_Accounts>();
            this.Setup_Accounts1 = new HashSet<Setup_Accounts>();
            this.Setup_Accounts2 = new HashSet<Setup_Accounts>();
            this.Setup_AccountsCashBankIdentification = new HashSet<Setup_AccountsCashBankIdentification>();
            this.Setup_AccountsControl = new HashSet<Setup_AccountsControl>();
            this.Setup_AccountsSubGroup = new HashSet<Setup_AccountsSubGroup>();
            this.Setup_AccountsSubsidiary = new HashSet<Setup_AccountsSubsidiary>();
            this.Setup_Bank = new HashSet<Setup_Bank>();
            this.Setup_Bank1 = new HashSet<Setup_Bank>();
            this.Setup_Brand = new HashSet<Setup_Brand>();
            this.Setup_Brand1 = new HashSet<Setup_Brand>();
            this.Setup_Capacity = new HashSet<Setup_Capacity>();
            this.Setup_Charge = new HashSet<Setup_Charge>();
            this.Setup_Color = new HashSet<Setup_Color>();
            this.Setup_ConvertionRatio = new HashSet<Setup_ConvertionRatio>();
            this.Setup_ConvertionRatio1 = new HashSet<Setup_ConvertionRatio>();
            this.Setup_CostingControl = new HashSet<Setup_CostingControl>();
            this.Setup_CostingControl1 = new HashSet<Setup_CostingControl>();
            this.Setup_CostingHead = new HashSet<Setup_CostingHead>();
            this.Setup_CostingHead1 = new HashSet<Setup_CostingHead>();
            this.Setup_Customer = new HashSet<Setup_Customer>();
            this.Setup_Customer1 = new HashSet<Setup_Customer>();
            this.Setup_CustomerGroup = new HashSet<Setup_CustomerGroup>();
            this.Setup_Designation = new HashSet<Setup_Designation>();
            this.Setup_DocumentsGroup = new HashSet<Setup_DocumentsGroup>();
            this.Setup_DocumentsGroup1 = new HashSet<Setup_DocumentsGroup>();
            this.Setup_DocumentsTitle = new HashSet<Setup_DocumentsTitle>();
            this.Setup_DocumentsTitle1 = new HashSet<Setup_DocumentsTitle>();
            this.Setup_Employee = new HashSet<Setup_Employee>();
            this.Setup_GeoDistrict = new HashSet<Setup_GeoDistrict>();
            this.Setup_GeoDivision = new HashSet<Setup_GeoDivision>();
            this.Setup_GeoPoliceStation = new HashSet<Setup_GeoPoliceStation>();
            this.Setup_GeoRegion = new HashSet<Setup_GeoRegion>();
            this.Setup_Location = new HashSet<Setup_Location>();
            this.Setup_Measurement = new HashSet<Setup_Measurement>();
            this.Setup_Port = new HashSet<Setup_Port>();
            this.Setup_Port1 = new HashSet<Setup_Port>();
            this.Setup_Price = new HashSet<Setup_Price>();
            this.Setup_PriceDetail = new HashSet<Setup_PriceDetail>();
            this.Setup_PriceType = new HashSet<Setup_PriceType>();
            this.Setup_Problem = new HashSet<Setup_Problem>();
            this.Setup_Problem1 = new HashSet<Setup_Problem>();
            this.Setup_Product = new HashSet<Setup_Product>();
            this.Setup_Product1 = new HashSet<Setup_Product>();
            this.Setup_ProductCategory = new HashSet<Setup_ProductCategory>();
            this.Setup_ProductCategory1 = new HashSet<Setup_ProductCategory>();
            this.Setup_ProductDimension = new HashSet<Setup_ProductDimension>();
            this.Setup_ProductGroup = new HashSet<Setup_ProductGroup>();
            this.Setup_ProductGroup1 = new HashSet<Setup_ProductGroup>();
            this.Setup_ProductSubGroup = new HashSet<Setup_ProductSubGroup>();
            this.Setup_ProductSubGroup1 = new HashSet<Setup_ProductSubGroup>();
            this.Setup_Profession = new HashSet<Setup_Profession>();
            this.Setup_Project = new HashSet<Setup_Project>();
            this.Setup_RelatedProduct = new HashSet<Setup_RelatedProduct>();
            this.Setup_Size = new HashSet<Setup_Size>();
            this.Setup_Style = new HashSet<Setup_Style>();
            this.Setup_Supplier = new HashSet<Setup_Supplier>();
            this.Setup_Supplier1 = new HashSet<Setup_Supplier>();
            this.Setup_SupplierGroup = new HashSet<Setup_SupplierGroup>();
            this.Setup_TemplateHeader = new HashSet<Setup_TemplateHeader>();
            this.Setup_TermsAndConditions = new HashSet<Setup_TermsAndConditions>();
            this.Setup_Transport = new HashSet<Setup_Transport>();
            this.Setup_TransportType = new HashSet<Setup_TransportType>();
            this.Setup_UnitType = new HashSet<Setup_UnitType>();
            this.Task_ChequeInfo = new HashSet<Task_ChequeInfo>();
            this.Task_ChequeTreatment = new HashSet<Task_ChequeTreatment>();
            this.Task_Collection = new HashSet<Task_Collection>();
            this.Task_Collection1 = new HashSet<Task_Collection>();
            this.Task_Collection2 = new HashSet<Task_Collection>();
            this.Task_Collection3 = new HashSet<Task_Collection>();
            this.Task_ComplainReceive = new HashSet<Task_ComplainReceive>();
            this.Task_ComplainReceive1 = new HashSet<Task_ComplainReceive>();
            this.Task_Convertion = new HashSet<Task_Convertion>();
            this.Task_Convertion1 = new HashSet<Task_Convertion>();
            this.Task_CustomerDelivery = new HashSet<Task_CustomerDelivery>();
            this.Task_CustomerDelivery1 = new HashSet<Task_CustomerDelivery>();
            this.Task_DeliveryChallan = new HashSet<Task_DeliveryChallan>();
            this.Task_DeliveryChallan1 = new HashSet<Task_DeliveryChallan>();
            this.Task_DeliveryChallan2 = new HashSet<Task_DeliveryChallan>();
            this.Task_GoodsReceive = new HashSet<Task_GoodsReceive>();
            this.Task_GoodsReceive1 = new HashSet<Task_GoodsReceive>();
            this.Task_GoodsReceive2 = new HashSet<Task_GoodsReceive>();
            this.Task_ImportCosting = new HashSet<Task_ImportCosting>();
            this.Task_ImportCosting1 = new HashSet<Task_ImportCosting>();
            this.Task_ImportDocuments = new HashSet<Task_ImportDocuments>();
            this.Task_ImportedStockIn = new HashSet<Task_ImportedStockIn>();
            this.Task_ImportedStockIn1 = new HashSet<Task_ImportedStockIn>();
            this.Task_ItemRequisition = new HashSet<Task_ItemRequisition>();
            this.Task_ItemRequisition1 = new HashSet<Task_ItemRequisition>();
            this.Task_LCOpening = new HashSet<Task_LCOpening>();
            this.Task_LCOpening1 = new HashSet<Task_LCOpening>();
            this.Task_LIMStockIn = new HashSet<Task_LIMStockIn>();
            this.Task_LIMStockIn1 = new HashSet<Task_LIMStockIn>();
            this.Task_PartyAdjustment = new HashSet<Task_PartyAdjustment>();
            this.Task_PartyAdjustment1 = new HashSet<Task_PartyAdjustment>();
            this.Task_Payment = new HashSet<Task_Payment>();
            this.Task_Payment1 = new HashSet<Task_Payment>();
            this.Task_Payment2 = new HashSet<Task_Payment>();
            this.Task_Payment3 = new HashSet<Task_Payment>();
            this.Task_PostedVoucher = new HashSet<Task_PostedVoucher>();
            this.Task_ProformaInvoice = new HashSet<Task_ProformaInvoice>();
            this.Task_ProformaInvoice1 = new HashSet<Task_ProformaInvoice>();
            this.Task_PurchaseOrder = new HashSet<Task_PurchaseOrder>();
            this.Task_PurchaseOrder1 = new HashSet<Task_PurchaseOrder>();
            this.Task_PurchaseReturn = new HashSet<Task_PurchaseReturn>();
            this.Task_PurchaseReturn1 = new HashSet<Task_PurchaseReturn>();
            this.Task_ReceiveFinalize = new HashSet<Task_ReceiveFinalize>();
            this.Task_ReceiveFinalize1 = new HashSet<Task_ReceiveFinalize>();
            this.Task_ReplacementClaim = new HashSet<Task_ReplacementClaim>();
            this.Task_ReplacementClaim1 = new HashSet<Task_ReplacementClaim>();
            this.Task_ReplacementReceive = new HashSet<Task_ReplacementReceive>();
            this.Task_ReplacementReceive1 = new HashSet<Task_ReplacementReceive>();
            this.Task_RequisitionFinalize = new HashSet<Task_RequisitionFinalize>();
            this.Task_RequisitionFinalize1 = new HashSet<Task_RequisitionFinalize>();
            this.Task_SalesInvoice = new HashSet<Task_SalesInvoice>();
            this.Task_SalesInvoice1 = new HashSet<Task_SalesInvoice>();
            this.Task_SalesInvoice2 = new HashSet<Task_SalesInvoice>();
            this.Task_SalesOrder = new HashSet<Task_SalesOrder>();
            this.Task_SalesOrder1 = new HashSet<Task_SalesOrder>();
            this.Task_SalesOrder2 = new HashSet<Task_SalesOrder>();
            this.Task_SalesQuotation = new HashSet<Task_SalesQuotation>();
            this.Task_SalesQuotation1 = new HashSet<Task_SalesQuotation>();
            this.Task_SalesReturn = new HashSet<Task_SalesReturn>();
            this.Task_SalesReturn1 = new HashSet<Task_SalesReturn>();
            this.Task_StockAdjustment = new HashSet<Task_StockAdjustment>();
            this.Task_StockAdjustment1 = new HashSet<Task_StockAdjustment>();
            this.Task_TransferChallan = new HashSet<Task_TransferChallan>();
            this.Task_TransferChallan1 = new HashSet<Task_TransferChallan>();
            this.Task_TransferOrder = new HashSet<Task_TransferOrder>();
            this.Task_TransferOrder1 = new HashSet<Task_TransferOrder>();
            this.Task_TransferReceive = new HashSet<Task_TransferReceive>();
            this.Task_TransferReceive1 = new HashSet<Task_TransferReceive>();
            this.Task_TransferRequisitionFinalize = new HashSet<Task_TransferRequisitionFinalize>();
            this.Task_TransferRequisitionFinalize1 = new HashSet<Task_TransferRequisitionFinalize>();
            this.Task_Voucher = new HashSet<Task_Voucher>();
            this.Task_Voucher1 = new HashSet<Task_Voucher>();
            this.Task_Voucher2 = new HashSet<Task_Voucher>();
            this.Task_Voucher3 = new HashSet<Task_Voucher>();
            this.Temp_AccountsLedgerOrProvisionalLedger = new HashSet<Temp_AccountsLedgerOrProvisionalLedger>();
            this.Temp_Collection = new HashSet<Temp_Collection>();
            this.Temp_Collection1 = new HashSet<Temp_Collection>();
            this.Temp_Collection2 = new HashSet<Temp_Collection>();
            this.Temp_CustomerSupplierOutstanding = new HashSet<Temp_CustomerSupplierOutstanding>();
            this.Temp_PartyLedger = new HashSet<Temp_PartyLedger>();
            this.Temp_SalesInvoice = new HashSet<Temp_SalesInvoice>();
            this.Temp_SalesInvoice1 = new HashSet<Temp_SalesInvoice>();
            this.Temp_TrialBalance = new HashSet<Temp_TrialBalance>();
        }
    
        public long SecurityUserId { get; set; }
        public long LevelId { get; set; }
        public long RoleId { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
        public string Active { get; set; }
        public string FirstLogin { get; set; }
        public short PasswordResetDays { get; set; }
        public System.DateTime LastResetDate { get; set; }
        public long CompanyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_CurrencyRate> Configuration_CurrencyRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_EventWiseCharge> Configuration_EventWiseCharge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_Features> Configuration_Features { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_GovtDutyRate_HSCode> Configuration_GovtDutyRate_HSCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_GovtDutyRate_Location> Configuration_GovtDutyRate_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Others_Documents> Others_Documents { get; set; }
        public virtual Security_Level Security_Level { get; set; }
        public virtual Security_Role Security_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Security_RoleWiseMenuPermission> Security_RoleWiseMenuPermission { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Security_UserLocation> Security_UserLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Security_UserWiseMenuPermission> Security_UserWiseMenuPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Security_UserWiseMenuPermission> Security_UserWiseMenuPermission1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Accounts> Setup_Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Accounts> Setup_Accounts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Accounts> Setup_Accounts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_AccountsCashBankIdentification> Setup_AccountsCashBankIdentification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_AccountsControl> Setup_AccountsControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_AccountsSubGroup> Setup_AccountsSubGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_AccountsSubsidiary> Setup_AccountsSubsidiary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Bank> Setup_Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Bank> Setup_Bank1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Brand> Setup_Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Brand> Setup_Brand1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Capacity> Setup_Capacity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Charge> Setup_Charge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Color> Setup_Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_ConvertionRatio> Setup_ConvertionRatio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_ConvertionRatio> Setup_ConvertionRatio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_CostingControl> Setup_CostingControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_CostingControl> Setup_CostingControl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_CostingHead> Setup_CostingHead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_CostingHead> Setup_CostingHead1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Customer> Setup_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Customer> Setup_Customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_CustomerGroup> Setup_CustomerGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Designation> Setup_Designation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_DocumentsGroup> Setup_DocumentsGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_DocumentsGroup> Setup_DocumentsGroup1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_DocumentsTitle> Setup_DocumentsTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_DocumentsTitle> Setup_DocumentsTitle1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_GeoDistrict> Setup_GeoDistrict { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_GeoDivision> Setup_GeoDivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_GeoPoliceStation> Setup_GeoPoliceStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_GeoRegion> Setup_GeoRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Location> Setup_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Measurement> Setup_Measurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Port> Setup_Port { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Port> Setup_Port1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Price> Setup_Price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_PriceDetail> Setup_PriceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_PriceType> Setup_PriceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Problem> Setup_Problem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Problem> Setup_Problem1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Product> Setup_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Product> Setup_Product1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_ProductCategory> Setup_ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_ProductCategory> Setup_ProductCategory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_ProductDimension> Setup_ProductDimension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_ProductGroup> Setup_ProductGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_ProductGroup> Setup_ProductGroup1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_ProductSubGroup> Setup_ProductSubGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_ProductSubGroup> Setup_ProductSubGroup1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Profession> Setup_Profession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Project> Setup_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_RelatedProduct> Setup_RelatedProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Size> Setup_Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Style> Setup_Style { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Supplier> Setup_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Supplier> Setup_Supplier1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_SupplierGroup> Setup_SupplierGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_TemplateHeader> Setup_TemplateHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_TermsAndConditions> Setup_TermsAndConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Transport> Setup_Transport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_TransportType> Setup_TransportType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_UnitType> Setup_UnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ChequeInfo> Task_ChequeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ChequeTreatment> Task_ChequeTreatment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Collection> Task_Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Collection> Task_Collection1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Collection> Task_Collection2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Collection> Task_Collection3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ComplainReceive> Task_ComplainReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ComplainReceive> Task_ComplainReceive1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Convertion> Task_Convertion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Convertion> Task_Convertion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_CustomerDelivery> Task_CustomerDelivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_CustomerDelivery> Task_CustomerDelivery1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_DeliveryChallan> Task_DeliveryChallan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_DeliveryChallan> Task_DeliveryChallan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_DeliveryChallan> Task_DeliveryChallan2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_GoodsReceive> Task_GoodsReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_GoodsReceive> Task_GoodsReceive1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_GoodsReceive> Task_GoodsReceive2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ImportCosting> Task_ImportCosting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ImportCosting> Task_ImportCosting1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ImportDocuments> Task_ImportDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ImportedStockIn> Task_ImportedStockIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ImportedStockIn> Task_ImportedStockIn1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ItemRequisition> Task_ItemRequisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ItemRequisition> Task_ItemRequisition1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_LCOpening> Task_LCOpening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_LCOpening> Task_LCOpening1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_LIMStockIn> Task_LIMStockIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_LIMStockIn> Task_LIMStockIn1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PartyAdjustment> Task_PartyAdjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PartyAdjustment> Task_PartyAdjustment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Payment> Task_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Payment> Task_Payment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Payment> Task_Payment2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Payment> Task_Payment3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PostedVoucher> Task_PostedVoucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ProformaInvoice> Task_ProformaInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ProformaInvoice> Task_ProformaInvoice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PurchaseOrder> Task_PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PurchaseOrder> Task_PurchaseOrder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PurchaseReturn> Task_PurchaseReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PurchaseReturn> Task_PurchaseReturn1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReceiveFinalize> Task_ReceiveFinalize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReceiveFinalize> Task_ReceiveFinalize1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReplacementClaim> Task_ReplacementClaim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReplacementClaim> Task_ReplacementClaim1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReplacementReceive> Task_ReplacementReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReplacementReceive> Task_ReplacementReceive1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_RequisitionFinalize> Task_RequisitionFinalize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_RequisitionFinalize> Task_RequisitionFinalize1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesInvoice> Task_SalesInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesInvoice> Task_SalesInvoice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesInvoice> Task_SalesInvoice2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesOrder> Task_SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesOrder> Task_SalesOrder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesOrder> Task_SalesOrder2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesQuotation> Task_SalesQuotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesQuotation> Task_SalesQuotation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesReturn> Task_SalesReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesReturn> Task_SalesReturn1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_StockAdjustment> Task_StockAdjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_StockAdjustment> Task_StockAdjustment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferChallan> Task_TransferChallan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferChallan> Task_TransferChallan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferOrder> Task_TransferOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferOrder> Task_TransferOrder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferReceive> Task_TransferReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferReceive> Task_TransferReceive1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferRequisitionFinalize> Task_TransferRequisitionFinalize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferRequisitionFinalize> Task_TransferRequisitionFinalize1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Voucher> Task_Voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Voucher> Task_Voucher1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Voucher> Task_Voucher2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Voucher> Task_Voucher3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_AccountsLedgerOrProvisionalLedger> Temp_AccountsLedgerOrProvisionalLedger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_Collection> Temp_Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_Collection> Temp_Collection1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_Collection> Temp_Collection2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_CustomerSupplierOutstanding> Temp_CustomerSupplierOutstanding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_PartyLedger> Temp_PartyLedger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_SalesInvoice> Temp_SalesInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_SalesInvoice> Temp_SalesInvoice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_TrialBalance> Temp_TrialBalance { get; set; }
    }
}
