//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_AccountsCashBankIdentification
    {
        public long IdentificationId { get; set; }
        public string IdentificationType { get; set; }
        public Nullable<long> AccountsControlId { get; set; }
        public Nullable<long> AccountsSubsidiaryId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Setup_AccountsControl Setup_AccountsControl { get; set; }
        public virtual Setup_AccountsSubsidiary Setup_AccountsSubsidiary { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
    }
}
