//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Setup_Customer()
        {
            this.Configuration_OperationalEventDetail = new HashSet<Configuration_OperationalEventDetail>();
            this.Task_Collection = new HashSet<Task_Collection>();
            this.Task_ComplainReceive = new HashSet<Task_ComplainReceive>();
            this.Task_CustomerDelivery = new HashSet<Task_CustomerDelivery>();
            this.Task_DeliveryChallan = new HashSet<Task_DeliveryChallan>();
            this.Task_DeliveryChallan1 = new HashSet<Task_DeliveryChallan>();
            this.Task_PartyAdjustmentDetail = new HashSet<Task_PartyAdjustmentDetail>();
            this.Task_SalesInvoice = new HashSet<Task_SalesInvoice>();
            this.Task_SalesInvoice1 = new HashSet<Task_SalesInvoice>();
            this.Task_SalesOrder = new HashSet<Task_SalesOrder>();
            this.Task_SalesOrder1 = new HashSet<Task_SalesOrder>();
            this.Task_SalesQuotation = new HashSet<Task_SalesQuotation>();
            this.Task_SalesQuotation1 = new HashSet<Task_SalesQuotation>();
            this.Task_SalesReturn = new HashSet<Task_SalesReturn>();
            this.Temp_Collection = new HashSet<Temp_Collection>();
            this.Temp_CustomerSupplierOutstanding = new HashSet<Temp_CustomerSupplierOutstanding>();
            this.Temp_PartyLedger = new HashSet<Temp_PartyLedger>();
            this.Temp_SalesInvoice = new HashSet<Temp_SalesInvoice>();
            this.Temp_SalesInvoice1 = new HashSet<Temp_SalesInvoice>();
        }
    
        public long CustomerId { get; set; }
        public long CustomerGroupId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string PhoneNo1 { get; set; }
        public string PhoneNo2 { get; set; }
        public long SalesPersonId { get; set; }
        public bool IsCombined { get; set; }
        public bool IsActive { get; set; }
        public string Type { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonMobile { get; set; }
        public Nullable<long> ProfessionId { get; set; }
        public string Designation { get; set; }
        public string ReferenceName { get; set; }
        public string ReferenceContactNo { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public decimal OpeningBalance { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public decimal ChequeDishonourBalance { get; set; }
        public Nullable<System.DateTime> ChequeDishonourOpeningDate { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal LedgerLimit { get; set; }
        public decimal CreditAllowedDays { get; set; }
        public bool IsLocked { get; set; }
        public bool IsRMALocked { get; set; }
        public Nullable<long> AccountsId { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public decimal OpeningBalance1 { get; set; }
        public decimal OpeningBalance2 { get; set; }
        public decimal ChequeDishonourBalance1 { get; set; }
        public decimal ChequeDishonourBalance2 { get; set; }
        public decimal CreditLimit1 { get; set; }
        public decimal CreditLimit2 { get; set; }
        public decimal LedgerLimit1 { get; set; }
        public decimal LedgerLimit2 { get; set; }
        public decimal CollectedAmount { get; set; }
        public decimal Collected1Amount { get; set; }
        public decimal Collected2Amount { get; set; }
        public string TransactionType { get; set; }
        public bool IsWalkIn { get; set; }
        public long CompanyId { get; set; }
        public long LocationId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<long> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_OperationalEventDetail> Configuration_OperationalEventDetail { get; set; }
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Setup_Accounts Setup_Accounts { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_CustomerGroup Setup_CustomerGroup { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_Profession Setup_Profession { get; set; }
        public virtual Setup_Supplier Setup_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Collection> Task_Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ComplainReceive> Task_ComplainReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_CustomerDelivery> Task_CustomerDelivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_DeliveryChallan> Task_DeliveryChallan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_DeliveryChallan> Task_DeliveryChallan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PartyAdjustmentDetail> Task_PartyAdjustmentDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesInvoice> Task_SalesInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesInvoice> Task_SalesInvoice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesOrder> Task_SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesOrder> Task_SalesOrder1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesQuotation> Task_SalesQuotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesQuotation> Task_SalesQuotation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesReturn> Task_SalesReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_Collection> Temp_Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_CustomerSupplierOutstanding> Temp_CustomerSupplierOutstanding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_PartyLedger> Temp_PartyLedger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_SalesInvoice> Temp_SalesInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_SalesInvoice> Temp_SalesInvoice1 { get; set; }
    }
}
