//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_PriceDetail
    {
        public long PriceDetailId { get; set; }
        public long PriceId { get; set; }
        public decimal Price { get; set; }
        public decimal Price1Rate { get; set; }
        public decimal Price1 { get; set; }
        public decimal Price2Rate { get; set; }
        public decimal Price2 { get; set; }
        public decimal LowerRangeQty { get; set; }
        public decimal UpperRangeQty { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Setup_Price Setup_Price { get; set; }
    }
}
