//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_RelatedProduct
    {
        public long RelatedProductId { get; set; }
        public long ProductId { get; set; }
        public long RelatedOrSpareProductId { get; set; }
        public string Type { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Setup_Product Setup_Product { get; set; }
        public virtual Setup_Product Setup_Product1 { get; set; }
    }
}
