//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Setup_Supplier()
        {
            this.Setup_Customer = new HashSet<Setup_Customer>();
            this.Stock_BadStock = new HashSet<Stock_BadStock>();
            this.Stock_CurrentStock = new HashSet<Stock_CurrentStock>();
            this.Stock_LIMStock = new HashSet<Stock_LIMStock>();
            this.Stock_RMAStock = new HashSet<Stock_RMAStock>();
            this.Stock_TransitStock = new HashSet<Stock_TransitStock>();
            this.Task_ConvertionDetail = new HashSet<Task_ConvertionDetail>();
            this.Task_DeliveryChallanDetail = new HashSet<Task_DeliveryChallanDetail>();
            this.Task_GoodsReceive = new HashSet<Task_GoodsReceive>();
            this.Task_LCOpening = new HashSet<Task_LCOpening>();
            this.Task_LCOpening1 = new HashSet<Task_LCOpening>();
            this.Task_PartyAdjustmentDetail = new HashSet<Task_PartyAdjustmentDetail>();
            this.Task_Payment = new HashSet<Task_Payment>();
            this.Task_ProformaInvoice = new HashSet<Task_ProformaInvoice>();
            this.Task_PurchaseOrder = new HashSet<Task_PurchaseOrder>();
            this.Task_PurchaseReturn = new HashSet<Task_PurchaseReturn>();
            this.Task_ReceiveFinalize = new HashSet<Task_ReceiveFinalize>();
            this.Task_ReplacementClaim = new HashSet<Task_ReplacementClaim>();
            this.Task_SalesInvoiceDetail = new HashSet<Task_SalesInvoiceDetail>();
            this.Task_SalesReturnDetail = new HashSet<Task_SalesReturnDetail>();
            this.Task_TransferChallanDetail = new HashSet<Task_TransferChallanDetail>();
            this.Task_TransferReceiveDetail = new HashSet<Task_TransferReceiveDetail>();
            this.Temp_CustomerSupplierOutstanding = new HashSet<Temp_CustomerSupplierOutstanding>();
            this.Temp_PartyLedger = new HashSet<Temp_PartyLedger>();
        }
    
        public long SupplierId { get; set; }
        public long SupplierGroupId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string URL { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonMobile { get; set; }
        public Nullable<long> ProfessionId { get; set; }
        public string Designation { get; set; }
        public Nullable<long> BankId { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNumber { get; set; }
        public Nullable<long> AccountsId { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public Nullable<System.DateTime> OpeningDate { get; set; }
        public decimal OpeningBalance { get; set; }
        public decimal OpeningBalance1 { get; set; }
        public decimal OpeningBalance2 { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal Paid1Amount { get; set; }
        public decimal Paid2Amount { get; set; }
        public bool IsActive { get; set; }
        public long CompanyId { get; set; }
        public long LocationId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<long> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Setup_Accounts Setup_Accounts { get; set; }
        public virtual Setup_Bank Setup_Bank { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Customer> Setup_Customer { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_Profession Setup_Profession { get; set; }
        public virtual Setup_SupplierGroup Setup_SupplierGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_BadStock> Stock_BadStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_CurrentStock> Stock_CurrentStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_LIMStock> Stock_LIMStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_RMAStock> Stock_RMAStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_TransitStock> Stock_TransitStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ConvertionDetail> Task_ConvertionDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_DeliveryChallanDetail> Task_DeliveryChallanDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_GoodsReceive> Task_GoodsReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_LCOpening> Task_LCOpening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_LCOpening> Task_LCOpening1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PartyAdjustmentDetail> Task_PartyAdjustmentDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Payment> Task_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ProformaInvoice> Task_ProformaInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PurchaseOrder> Task_PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PurchaseReturn> Task_PurchaseReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReceiveFinalize> Task_ReceiveFinalize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReplacementClaim> Task_ReplacementClaim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesInvoiceDetail> Task_SalesInvoiceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesReturnDetail> Task_SalesReturnDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferChallanDetail> Task_TransferChallanDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferReceiveDetail> Task_TransferReceiveDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_CustomerSupplierOutstanding> Temp_CustomerSupplierOutstanding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_PartyLedger> Temp_PartyLedger { get; set; }
    }
}
