//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_AccountsDetail_Location
    {
        public System.Guid AccountsDetailId { get; set; }
        public long AccountsId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public decimal OpeningBalance { get; set; }
        public decimal OpeningBalance1 { get; set; }
        public decimal OpeningBalance2 { get; set; }
    
        public virtual Setup_Accounts Setup_Accounts { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
    }
}
