//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Setup_Company()
        {
            this.Configuration_Code = new HashSet<Configuration_Code>();
            this.Configuration_CurrencyRate = new HashSet<Configuration_CurrencyRate>();
            this.Configuration_EventWiseCharge = new HashSet<Configuration_EventWiseCharge>();
            this.Configuration_Features = new HashSet<Configuration_Features>();
            this.Configuration_OperationalEventDetail = new HashSet<Configuration_OperationalEventDetail>();
            this.Configuration_Voucher = new HashSet<Configuration_Voucher>();
            this.Others_Documents = new HashSet<Others_Documents>();
            this.Others_ReportDesignConfig = new HashSet<Others_ReportDesignConfig>();
            this.Security_Level = new HashSet<Security_Level>();
            this.Security_Role = new HashSet<Security_Role>();
            this.Security_RoleWiseMenuPermission = new HashSet<Security_RoleWiseMenuPermission>();
            this.Security_User = new HashSet<Security_User>();
            this.Security_UserWiseMenuPermission = new HashSet<Security_UserWiseMenuPermission>();
            this.Setup_Accounts = new HashSet<Setup_Accounts>();
            this.Setup_AccountsCashBankIdentification = new HashSet<Setup_AccountsCashBankIdentification>();
            this.Setup_AccountsControl = new HashSet<Setup_AccountsControl>();
            this.Setup_AccountsGroup = new HashSet<Setup_AccountsGroup>();
            this.Setup_AccountsSubGroup = new HashSet<Setup_AccountsSubGroup>();
            this.Setup_AccountsSubsidiary = new HashSet<Setup_AccountsSubsidiary>();
            this.Setup_Bank = new HashSet<Setup_Bank>();
            this.Setup_Brand = new HashSet<Setup_Brand>();
            this.Setup_Capacity = new HashSet<Setup_Capacity>();
            this.Setup_Charge = new HashSet<Setup_Charge>();
            this.Setup_Color = new HashSet<Setup_Color>();
            this.Setup_ConvertionRatio = new HashSet<Setup_ConvertionRatio>();
            this.Setup_CostingControl = new HashSet<Setup_CostingControl>();
            this.Setup_CostingHead = new HashSet<Setup_CostingHead>();
            this.Setup_Customer = new HashSet<Setup_Customer>();
            this.Setup_CustomerGroup = new HashSet<Setup_CustomerGroup>();
            this.Setup_Designation = new HashSet<Setup_Designation>();
            this.Setup_DocumentsGroup = new HashSet<Setup_DocumentsGroup>();
            this.Setup_DocumentsTitle = new HashSet<Setup_DocumentsTitle>();
            this.Setup_Employee = new HashSet<Setup_Employee>();
            this.Setup_GeoDistrict = new HashSet<Setup_GeoDistrict>();
            this.Setup_GeoDivision = new HashSet<Setup_GeoDivision>();
            this.Setup_GeoPoliceStation = new HashSet<Setup_GeoPoliceStation>();
            this.Setup_GeoRegion = new HashSet<Setup_GeoRegion>();
            this.Setup_Location = new HashSet<Setup_Location>();
            this.Setup_Measurement = new HashSet<Setup_Measurement>();
            this.Setup_Port = new HashSet<Setup_Port>();
            this.Setup_Price = new HashSet<Setup_Price>();
            this.Setup_PriceType = new HashSet<Setup_PriceType>();
            this.Setup_Problem = new HashSet<Setup_Problem>();
            this.Setup_Product = new HashSet<Setup_Product>();
            this.Setup_ProductCategory = new HashSet<Setup_ProductCategory>();
            this.Setup_ProductGroup = new HashSet<Setup_ProductGroup>();
            this.Setup_ProductSubGroup = new HashSet<Setup_ProductSubGroup>();
            this.Setup_Profession = new HashSet<Setup_Profession>();
            this.Setup_Project = new HashSet<Setup_Project>();
            this.Setup_Size = new HashSet<Setup_Size>();
            this.Setup_Style = new HashSet<Setup_Style>();
            this.Setup_Supplier = new HashSet<Setup_Supplier>();
            this.Setup_SupplierGroup = new HashSet<Setup_SupplierGroup>();
            this.Setup_TemplateHeader = new HashSet<Setup_TemplateHeader>();
            this.Setup_TermsAndConditions = new HashSet<Setup_TermsAndConditions>();
            this.Setup_Transport = new HashSet<Setup_Transport>();
            this.Setup_TransportType = new HashSet<Setup_TransportType>();
            this.Setup_UnitType = new HashSet<Setup_UnitType>();
            this.Stock_BadStock = new HashSet<Stock_BadStock>();
            this.Stock_CurrentStock = new HashSet<Stock_CurrentStock>();
            this.Stock_LIMStock = new HashSet<Stock_LIMStock>();
            this.Stock_RMAStock = new HashSet<Stock_RMAStock>();
            this.Stock_TransitStock = new HashSet<Stock_TransitStock>();
            this.Task_ChequeInfo = new HashSet<Task_ChequeInfo>();
            this.Task_Collection = new HashSet<Task_Collection>();
            this.Task_CollectionNos = new HashSet<Task_CollectionNos>();
            this.Task_ComplainReceive = new HashSet<Task_ComplainReceive>();
            this.Task_ComplainReceiveNos = new HashSet<Task_ComplainReceiveNos>();
            this.Task_Convertion = new HashSet<Task_Convertion>();
            this.Task_ConvertionNos = new HashSet<Task_ConvertionNos>();
            this.Task_CustomerDelivery = new HashSet<Task_CustomerDelivery>();
            this.Task_CustomerDeliveryNos = new HashSet<Task_CustomerDeliveryNos>();
            this.Task_DeliveryChallan = new HashSet<Task_DeliveryChallan>();
            this.Task_DeliveryChallanNos = new HashSet<Task_DeliveryChallanNos>();
            this.Task_GoodsReceive = new HashSet<Task_GoodsReceive>();
            this.Task_GoodsReceiveNos = new HashSet<Task_GoodsReceiveNos>();
            this.Task_ImportCosting = new HashSet<Task_ImportCosting>();
            this.Task_ImportCostingNos = new HashSet<Task_ImportCostingNos>();
            this.Task_ImportedStockIn = new HashSet<Task_ImportedStockIn>();
            this.Task_ImportedStockInNos = new HashSet<Task_ImportedStockInNos>();
            this.Task_ItemRequisition = new HashSet<Task_ItemRequisition>();
            this.Task_ItemRequisitionNos = new HashSet<Task_ItemRequisitionNos>();
            this.Task_LCOpening = new HashSet<Task_LCOpening>();
            this.Task_LCOpeningNos = new HashSet<Task_LCOpeningNos>();
            this.Task_LIMStockIn = new HashSet<Task_LIMStockIn>();
            this.Task_LIMStockInNos = new HashSet<Task_LIMStockInNos>();
            this.Task_PartyAdjustment = new HashSet<Task_PartyAdjustment>();
            this.Task_PartyAdjustmentNos = new HashSet<Task_PartyAdjustmentNos>();
            this.Task_Payment = new HashSet<Task_Payment>();
            this.Task_PaymentNos = new HashSet<Task_PaymentNos>();
            this.Task_PostedVoucher = new HashSet<Task_PostedVoucher>();
            this.Task_ProformaInvoice = new HashSet<Task_ProformaInvoice>();
            this.Task_ProformaInvoiceNos = new HashSet<Task_ProformaInvoiceNos>();
            this.Task_PurchaseOrder = new HashSet<Task_PurchaseOrder>();
            this.Task_PurchaseOrderNos = new HashSet<Task_PurchaseOrderNos>();
            this.Task_PurchaseReturn = new HashSet<Task_PurchaseReturn>();
            this.Task_PurchaseReturnNos = new HashSet<Task_PurchaseReturnNos>();
            this.Task_ReceiveFinalize = new HashSet<Task_ReceiveFinalize>();
            this.Task_ReceiveFinalizeNos = new HashSet<Task_ReceiveFinalizeNos>();
            this.Task_ReplacementClaim = new HashSet<Task_ReplacementClaim>();
            this.Task_ReplacementClaimNos = new HashSet<Task_ReplacementClaimNos>();
            this.Task_ReplacementReceive = new HashSet<Task_ReplacementReceive>();
            this.Task_ReplacementReceiveNos = new HashSet<Task_ReplacementReceiveNos>();
            this.Task_RequisitionFinalize = new HashSet<Task_RequisitionFinalize>();
            this.Task_RequisitionFinalizeNos = new HashSet<Task_RequisitionFinalizeNos>();
            this.Task_SalesInvoice = new HashSet<Task_SalesInvoice>();
            this.Task_SalesInvoiceNos = new HashSet<Task_SalesInvoiceNos>();
            this.Task_SalesOrder = new HashSet<Task_SalesOrder>();
            this.Task_SalesOrderNos = new HashSet<Task_SalesOrderNos>();
            this.Task_SalesQuotation = new HashSet<Task_SalesQuotation>();
            this.Task_SalesQuotationNos = new HashSet<Task_SalesQuotationNos>();
            this.Task_SalesReturn = new HashSet<Task_SalesReturn>();
            this.Task_SalesReturnNos = new HashSet<Task_SalesReturnNos>();
            this.Task_StockAdjustment = new HashSet<Task_StockAdjustment>();
            this.Task_StockAdjustmentNos = new HashSet<Task_StockAdjustmentNos>();
            this.Task_TransferChallan = new HashSet<Task_TransferChallan>();
            this.Task_TransferChallanNos = new HashSet<Task_TransferChallanNos>();
            this.Task_TransferOrder = new HashSet<Task_TransferOrder>();
            this.Task_TransferOrderNos = new HashSet<Task_TransferOrderNos>();
            this.Task_TransferReceive = new HashSet<Task_TransferReceive>();
            this.Task_TransferReceiveNos = new HashSet<Task_TransferReceiveNos>();
            this.Task_TransferRequisitionFinalize = new HashSet<Task_TransferRequisitionFinalize>();
            this.Task_TransferRequisitionFinalizeNos = new HashSet<Task_TransferRequisitionFinalizeNos>();
            this.Task_Voucher = new HashSet<Task_Voucher>();
            this.Task_VoucherNos = new HashSet<Task_VoucherNos>();
            this.Temp_AccountsLedgerOrProvisionalLedger = new HashSet<Temp_AccountsLedgerOrProvisionalLedger>();
            this.Temp_Collection = new HashSet<Temp_Collection>();
            this.Temp_CustomerSupplierOutstanding = new HashSet<Temp_CustomerSupplierOutstanding>();
            this.Temp_PartyLedger = new HashSet<Temp_PartyLedger>();
            this.Temp_SalesInvoice = new HashSet<Temp_SalesInvoice>();
            this.Temp_TrialBalance = new HashSet<Temp_TrialBalance>();
        }
    
        public long CompanyId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string FaxNo { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public string BaseCurrency { get; set; }
        public string Currency1 { get; set; }
        public string Currency2 { get; set; }
        public string VATRegNo { get; set; }
        public byte FinStartingMonth { get; set; }
        public byte GovtFinStartingMonth { get; set; }
        public short MaxWidthInPixel { get; set; }
        public short MaxHeightInPixel { get; set; }
        public Nullable<System.DateTime> CompanyOpeningDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_Code> Configuration_Code { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_CurrencyRate> Configuration_CurrencyRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_EventWiseCharge> Configuration_EventWiseCharge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_Features> Configuration_Features { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_OperationalEventDetail> Configuration_OperationalEventDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_Voucher> Configuration_Voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Others_Documents> Others_Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Others_ReportDesignConfig> Others_ReportDesignConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Security_Level> Security_Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Security_Role> Security_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Security_RoleWiseMenuPermission> Security_RoleWiseMenuPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Security_User> Security_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Security_UserWiseMenuPermission> Security_UserWiseMenuPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Accounts> Setup_Accounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_AccountsCashBankIdentification> Setup_AccountsCashBankIdentification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_AccountsControl> Setup_AccountsControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_AccountsGroup> Setup_AccountsGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_AccountsSubGroup> Setup_AccountsSubGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_AccountsSubsidiary> Setup_AccountsSubsidiary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Bank> Setup_Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Brand> Setup_Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Capacity> Setup_Capacity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Charge> Setup_Charge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Color> Setup_Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_ConvertionRatio> Setup_ConvertionRatio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_CostingControl> Setup_CostingControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_CostingHead> Setup_CostingHead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Customer> Setup_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_CustomerGroup> Setup_CustomerGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Designation> Setup_Designation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_DocumentsGroup> Setup_DocumentsGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_DocumentsTitle> Setup_DocumentsTitle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_GeoDistrict> Setup_GeoDistrict { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_GeoDivision> Setup_GeoDivision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_GeoPoliceStation> Setup_GeoPoliceStation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_GeoRegion> Setup_GeoRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Location> Setup_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Measurement> Setup_Measurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Port> Setup_Port { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Price> Setup_Price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_PriceType> Setup_PriceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Problem> Setup_Problem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Product> Setup_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_ProductCategory> Setup_ProductCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_ProductGroup> Setup_ProductGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_ProductSubGroup> Setup_ProductSubGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Profession> Setup_Profession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Project> Setup_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Size> Setup_Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Style> Setup_Style { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Supplier> Setup_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_SupplierGroup> Setup_SupplierGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_TemplateHeader> Setup_TemplateHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_TermsAndConditions> Setup_TermsAndConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Transport> Setup_Transport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_TransportType> Setup_TransportType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_UnitType> Setup_UnitType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_BadStock> Stock_BadStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_CurrentStock> Stock_CurrentStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_LIMStock> Stock_LIMStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_RMAStock> Stock_RMAStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock_TransitStock> Stock_TransitStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ChequeInfo> Task_ChequeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Collection> Task_Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_CollectionNos> Task_CollectionNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ComplainReceive> Task_ComplainReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ComplainReceiveNos> Task_ComplainReceiveNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Convertion> Task_Convertion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ConvertionNos> Task_ConvertionNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_CustomerDelivery> Task_CustomerDelivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_CustomerDeliveryNos> Task_CustomerDeliveryNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_DeliveryChallan> Task_DeliveryChallan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_DeliveryChallanNos> Task_DeliveryChallanNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_GoodsReceive> Task_GoodsReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_GoodsReceiveNos> Task_GoodsReceiveNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ImportCosting> Task_ImportCosting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ImportCostingNos> Task_ImportCostingNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ImportedStockIn> Task_ImportedStockIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ImportedStockInNos> Task_ImportedStockInNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ItemRequisition> Task_ItemRequisition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ItemRequisitionNos> Task_ItemRequisitionNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_LCOpening> Task_LCOpening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_LCOpeningNos> Task_LCOpeningNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_LIMStockIn> Task_LIMStockIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_LIMStockInNos> Task_LIMStockInNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PartyAdjustment> Task_PartyAdjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PartyAdjustmentNos> Task_PartyAdjustmentNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Payment> Task_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PaymentNos> Task_PaymentNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PostedVoucher> Task_PostedVoucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ProformaInvoice> Task_ProformaInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ProformaInvoiceNos> Task_ProformaInvoiceNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PurchaseOrder> Task_PurchaseOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PurchaseOrderNos> Task_PurchaseOrderNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PurchaseReturn> Task_PurchaseReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PurchaseReturnNos> Task_PurchaseReturnNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReceiveFinalize> Task_ReceiveFinalize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReceiveFinalizeNos> Task_ReceiveFinalizeNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReplacementClaim> Task_ReplacementClaim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReplacementClaimNos> Task_ReplacementClaimNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReplacementReceive> Task_ReplacementReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReplacementReceiveNos> Task_ReplacementReceiveNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_RequisitionFinalize> Task_RequisitionFinalize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_RequisitionFinalizeNos> Task_RequisitionFinalizeNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesInvoice> Task_SalesInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesInvoiceNos> Task_SalesInvoiceNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesOrder> Task_SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesOrderNos> Task_SalesOrderNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesQuotation> Task_SalesQuotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesQuotationNos> Task_SalesQuotationNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesReturn> Task_SalesReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesReturnNos> Task_SalesReturnNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_StockAdjustment> Task_StockAdjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_StockAdjustmentNos> Task_StockAdjustmentNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferChallan> Task_TransferChallan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferChallanNos> Task_TransferChallanNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferOrder> Task_TransferOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferOrderNos> Task_TransferOrderNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferReceive> Task_TransferReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferReceiveNos> Task_TransferReceiveNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferRequisitionFinalize> Task_TransferRequisitionFinalize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferRequisitionFinalizeNos> Task_TransferRequisitionFinalizeNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Voucher> Task_Voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_VoucherNos> Task_VoucherNos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_AccountsLedgerOrProvisionalLedger> Temp_AccountsLedgerOrProvisionalLedger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_Collection> Temp_Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_CustomerSupplierOutstanding> Temp_CustomerSupplierOutstanding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_PartyLedger> Temp_PartyLedger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_SalesInvoice> Temp_SalesInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_TrialBalance> Temp_TrialBalance { get; set; }
    }
}
