//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_Accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Setup_Accounts()
        {
            this.Configuration_EventWiseCharge = new HashSet<Configuration_EventWiseCharge>();
            this.Configuration_VoucherDetail = new HashSet<Configuration_VoucherDetail>();
            this.Setup_AccountsDetail_Location = new HashSet<Setup_AccountsDetail_Location>();
            this.Setup_Bank = new HashSet<Setup_Bank>();
            this.Setup_CostingHead = new HashSet<Setup_CostingHead>();
            this.Setup_Customer = new HashSet<Setup_Customer>();
            this.Setup_Employee = new HashSet<Setup_Employee>();
            this.Setup_GovtDuty = new HashSet<Setup_GovtDuty>();
            this.Setup_GovtDutyAdjustment = new HashSet<Setup_GovtDutyAdjustment>();
            this.Setup_Product = new HashSet<Setup_Product>();
            this.Setup_Supplier = new HashSet<Setup_Supplier>();
            this.Task_PostedVoucher = new HashSet<Task_PostedVoucher>();
            this.Task_VoucherDetail = new HashSet<Task_VoucherDetail>();
            this.Temp_TrialBalance = new HashSet<Temp_TrialBalance>();
        }
    
        public long AccountsId { get; set; }
        public long AccountsSubsidiaryId { get; set; }
        public string Name { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public string BalanceType { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public decimal OpeningBalance { get; set; }
        public decimal OpeningBalance1 { get; set; }
        public decimal OpeningBalance2 { get; set; }
        public bool IsOpeningFinalized { get; set; }
        public Nullable<byte> CategorizationId { get; set; }
        public long CompanyId { get; set; }
        public long LocationId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<long> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public Nullable<long> OpeningEditedBy { get; set; }
        public Nullable<System.DateTime> OpeningEditedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_EventWiseCharge> Configuration_EventWiseCharge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_VoucherDetail> Configuration_VoucherDetail { get; set; }
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Security_User Security_User2 { get; set; }
        public virtual Setup_AccountsSubsidiary Setup_AccountsSubsidiary { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_AccountsDetail_Location> Setup_AccountsDetail_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Bank> Setup_Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_CostingHead> Setup_CostingHead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Customer> Setup_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Employee> Setup_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_GovtDuty> Setup_GovtDuty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_GovtDutyAdjustment> Setup_GovtDutyAdjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Product> Setup_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Supplier> Setup_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PostedVoucher> Task_PostedVoucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_VoucherDetail> Task_VoucherDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_TrialBalance> Temp_TrialBalance { get; set; }
    }
}
