//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_HSCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Setup_HSCode()
        {
            this.Configuration_GovtDutyRate_HSCode = new HashSet<Configuration_GovtDutyRate_HSCode>();
            this.Setup_Product = new HashSet<Setup_Product>();
        }
    
        public long HSCodeId { get; set; }
        public string HSCode { get; set; }
        public string Description { get; set; }
        public string DetailDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration_GovtDutyRate_HSCode> Configuration_GovtDutyRate_HSCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_Product> Setup_Product { get; set; }
    }
}
