//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setup_AccountsSubGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Setup_AccountsSubGroup()
        {
            this.Setup_AccountsControl = new HashSet<Setup_AccountsControl>();
        }
    
        public long AccountsSubGroupId { get; set; }
        public long AccountsGroupId { get; set; }
        public string Name { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Setup_AccountsControl> Setup_AccountsControl { get; set; }
        public virtual Setup_AccountsGroup Setup_AccountsGroup { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
    }
}
