//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_TransitStockSerial
    {
        public System.Guid TransitStockSerialId { get; set; }
        public System.Guid TransitStockId { get; set; }
        public string Serial { get; set; }
        public string AdditionalSerial { get; set; }
    
        public virtual Stock_TransitStock Stock_TransitStock { get; set; }
    }
}
