//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_DeliveryChallanDetail_GovtDuty
    {
        public System.Guid Id { get; set; }
        public System.Guid ChallanDetailId { get; set; }
        public long GovtDutyId { get; set; }
        public string RateType { get; set; }
        public decimal RateValue { get; set; }
        public decimal RateValue1 { get; set; }
        public decimal RateValue2 { get; set; }
        public decimal RateAmount { get; set; }
        public decimal RateAmount1 { get; set; }
        public decimal RateAmount2 { get; set; }
        public string ExemptedType { get; set; }
        public decimal ExemptedValue { get; set; }
        public decimal ExemptedValue1 { get; set; }
        public decimal ExemptedValue2 { get; set; }
        public decimal ExemptedAmount { get; set; }
        public decimal ExemptedAmount1 { get; set; }
        public decimal ExemptedAmount2 { get; set; }
    
        public virtual Setup_GovtDuty Setup_GovtDuty { get; set; }
        public virtual Task_DeliveryChallanDetail Task_DeliveryChallanDetail { get; set; }
    }
}
