//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_SalesQuotationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_SalesQuotationDetail()
        {
            this.Task_SalesQuotationDetail_GovtDuty = new HashSet<Task_SalesQuotationDetail_GovtDuty>();
        }
    
        public System.Guid QuotaionDetailId { get; set; }
        public System.Guid QuotationId { get; set; }
        public long ProductId { get; set; }
        public Nullable<long> ProductDimensionId { get; set; }
        public long UnitTypeId { get; set; }
        public decimal Quantity { get; set; }
        public decimal OrderedQuantity { get; set; }
        public decimal Price { get; set; }
        public decimal Price1 { get; set; }
        public decimal Price2 { get; set; }
        public string DiscountType { get; set; }
        public decimal DiscountValue { get; set; }
        public decimal Discount1Value { get; set; }
        public decimal Discount2Value { get; set; }
        public decimal Discount { get; set; }
        public decimal Discount1 { get; set; }
        public decimal Discount2 { get; set; }
        public string AdditionalDescription { get; set; }
        public bool IsSampleRequired { get; set; }
        public string SampleProvidedBy { get; set; }
        public Nullable<System.DateTime> SampleProvidedDate { get; set; }
        public Nullable<long> RequestedBy { get; set; }
    
        public virtual Setup_Employee Setup_Employee { get; set; }
        public virtual Setup_Product Setup_Product { get; set; }
        public virtual Setup_ProductDimension Setup_ProductDimension { get; set; }
        public virtual Setup_UnitType Setup_UnitType { get; set; }
        public virtual Task_SalesQuotation Task_SalesQuotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesQuotationDetail_GovtDuty> Task_SalesQuotationDetail_GovtDuty { get; set; }
    }
}
