//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_DeliveryChallan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_DeliveryChallan()
        {
            this.Task_DeliveryChallan_Charge = new HashSet<Task_DeliveryChallan_Charge>();
            this.Task_DeliveryChallanDetail = new HashSet<Task_DeliveryChallanDetail>();
            this.Task_SalesInvoiceDetail = new HashSet<Task_SalesInvoiceDetail>();
        }
    
        public System.Guid ChallanId { get; set; }
        public string ChallanNo { get; set; }
        public System.DateTime ChallanDate { get; set; }
        public long CustomerId { get; set; }
        public string CustomerDetail { get; set; }
        public Nullable<long> BuyerId { get; set; }
        public System.Guid SalesOrderId { get; set; }
        public long DeliveryFromId { get; set; }
        public string DeliveryPlace { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonNo { get; set; }
        public Nullable<long> TransportId { get; set; }
        public Nullable<long> TransportTypeId { get; set; }
        public string VehicleNo { get; set; }
        public string DriverName { get; set; }
        public string DriverContactNo { get; set; }
        public bool IsSettledByInvoice { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public string TransactionFrom { get; set; }
        public string GovtDutyChallanNo { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<long> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Security_User Security_User2 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Customer Setup_Customer { get; set; }
        public virtual Setup_Customer Setup_Customer1 { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_Location Setup_Location1 { get; set; }
        public virtual Setup_Transport Setup_Transport { get; set; }
        public virtual Setup_TransportType Setup_TransportType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_DeliveryChallan_Charge> Task_DeliveryChallan_Charge { get; set; }
        public virtual Task_SalesOrder Task_SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_DeliveryChallanDetail> Task_DeliveryChallanDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesInvoiceDetail> Task_SalesInvoiceDetail { get; set; }
    }
}
