//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_CustomerDeliveryDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_CustomerDeliveryDetail()
        {
            this.Task_CustomerDeliveryDetail_Problem = new HashSet<Task_CustomerDeliveryDetail_Problem>();
            this.Task_CustomerDeliveryDetail_SpareProduct = new HashSet<Task_CustomerDeliveryDetail_SpareProduct>();
        }
    
        public System.Guid DeliveryDetailId { get; set; }
        public System.Guid DeliveryId { get; set; }
        public System.Guid ComplainReceiveId { get; set; }
        public long PreviousProductId { get; set; }
        public Nullable<long> PreviousProductDimensionId { get; set; }
        public long PreviousUnitTypeId { get; set; }
        public string PreviousSerial { get; set; }
        public long NewProductId { get; set; }
        public Nullable<long> NewProductDimensionId { get; set; }
        public long NewUnitTypeId { get; set; }
        public string NewSerial { get; set; }
        public decimal Cost { get; set; }
        public decimal Cost1 { get; set; }
        public decimal Cost2 { get; set; }
        public bool IsAdjustmentRequired { get; set; }
        public string AdjustmentType { get; set; }
        public decimal AdjustedAmount { get; set; }
        public decimal AdjustedAmount1 { get; set; }
        public decimal AdjustedAmount2 { get; set; }
        public long DeliveryType { get; set; }
        public decimal TotalSpareAmount { get; set; }
        public decimal TotalSpareAmount1 { get; set; }
        public decimal TotalSpareAmount2 { get; set; }
        public decimal TotalSpareDiscount { get; set; }
        public decimal TotalSpareDiscount1 { get; set; }
        public decimal TotalSpareDiscount2 { get; set; }
        public decimal TotalServiceAmount { get; set; }
        public decimal TotalServiceAmount1 { get; set; }
        public decimal TotalServiceAmount2 { get; set; }
        public decimal TotalServiceDiscount { get; set; }
        public decimal TotalServiceDiscount1 { get; set; }
        public decimal TotalServiceDiscount2 { get; set; }
    
        public virtual Setup_Product Setup_Product { get; set; }
        public virtual Setup_Product Setup_Product1 { get; set; }
        public virtual Setup_ProductDimension Setup_ProductDimension { get; set; }
        public virtual Setup_ProductDimension Setup_ProductDimension1 { get; set; }
        public virtual Setup_UnitType Setup_UnitType { get; set; }
        public virtual Setup_UnitType Setup_UnitType1 { get; set; }
        public virtual Task_ComplainReceive Task_ComplainReceive { get; set; }
        public virtual Task_CustomerDelivery Task_CustomerDelivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_CustomerDeliveryDetail_Problem> Task_CustomerDeliveryDetail_Problem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_CustomerDeliveryDetail_SpareProduct> Task_CustomerDeliveryDetail_SpareProduct { get; set; }
    }
}
