//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_CustomerDelivery_Charge
    {
        public System.Guid DeliveryChargeId { get; set; }
        public System.Guid DeliveryId { get; set; }
        public long ChargeEventId { get; set; }
        public decimal ChargeAmount { get; set; }
        public decimal Charge1Amount { get; set; }
        public decimal Charge2Amount { get; set; }
    
        public virtual Configuration_EventWiseCharge Configuration_EventWiseCharge { get; set; }
        public virtual Task_CustomerDelivery Task_CustomerDelivery { get; set; }
    }
}
