//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_Voucher()
        {
            this.Task_ChequeInfo = new HashSet<Task_ChequeInfo>();
            this.Task_ChequeTreatment = new HashSet<Task_ChequeTreatment>();
            this.Task_Collection = new HashSet<Task_Collection>();
            this.Task_CollectionDetail = new HashSet<Task_CollectionDetail>();
            this.Task_CustomerDelivery = new HashSet<Task_CustomerDelivery>();
            this.Task_GoodsReceive = new HashSet<Task_GoodsReceive>();
            this.Task_PartyAdjustment = new HashSet<Task_PartyAdjustment>();
            this.Task_Payment = new HashSet<Task_Payment>();
            this.Task_PaymentDetail = new HashSet<Task_PaymentDetail>();
            this.Task_PurchaseReturn = new HashSet<Task_PurchaseReturn>();
            this.Task_ReceiveFinalize = new HashSet<Task_ReceiveFinalize>();
            this.Task_ReplacementClaim = new HashSet<Task_ReplacementClaim>();
            this.Task_ReplacementReceive = new HashSet<Task_ReplacementReceive>();
            this.Task_SalesInvoice = new HashSet<Task_SalesInvoice>();
            this.Task_SalesReturn = new HashSet<Task_SalesReturn>();
            this.Task_VoucherDetail = new HashSet<Task_VoucherDetail>();
        }
    
        public System.Guid VoucherId { get; set; }
        public string VoucherNo { get; set; }
        public System.DateTime Date { get; set; }
        public string VoucherType { get; set; }
        public string OperationType { get; set; }
        public string Description { get; set; }
        public string SelectedCurrency { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public bool Posted { get; set; }
        public Nullable<long> PostedBy { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<long> OperationalEventId { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<long> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        public virtual Configuration_OperationalEvent Configuration_OperationalEvent { get; set; }
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Security_User Security_User2 { get; set; }
        public virtual Security_User Security_User3 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ChequeInfo> Task_ChequeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ChequeTreatment> Task_ChequeTreatment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Collection> Task_Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_CollectionDetail> Task_CollectionDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_CustomerDelivery> Task_CustomerDelivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_GoodsReceive> Task_GoodsReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PartyAdjustment> Task_PartyAdjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Payment> Task_Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PaymentDetail> Task_PaymentDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PurchaseReturn> Task_PurchaseReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReceiveFinalize> Task_ReceiveFinalize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReplacementClaim> Task_ReplacementClaim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReplacementReceive> Task_ReplacementReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesInvoice> Task_SalesInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesReturn> Task_SalesReturn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_VoucherDetail> Task_VoucherDetail { get; set; }
    }
}
