//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_SalesQuotation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_SalesQuotation()
        {
            this.Task_SalesQuotation_Charge = new HashSet<Task_SalesQuotation_Charge>();
            this.Task_SalesQuotation_GovtDutyAdjustment = new HashSet<Task_SalesQuotation_GovtDutyAdjustment>();
            this.Task_SalesQuotation_Header = new HashSet<Task_SalesQuotation_Header>();
            this.Task_SalesQuotation_SecurityAndBanking = new HashSet<Task_SalesQuotation_SecurityAndBanking>();
            this.Task_SalesQuotation_DeliveryInfo = new HashSet<Task_SalesQuotation_DeliveryInfo>();
            this.Task_SalesQuotationDetail = new HashSet<Task_SalesQuotationDetail>();
        }
    
        public System.Guid QuotationId { get; set; }
        public string QuotationNo { get; set; }
        public System.DateTime QuotationDate { get; set; }
        public long CustomerId { get; set; }
        public string CustomerDetail { get; set; }
        public Nullable<long> OriginalBuyerId { get; set; }
        public long SalesPersonId { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public long OperationTypeId { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<long> TermsAndConditionsId { get; set; }
        public string TermsAndConditionsDetail { get; set; }
        public long PaymentModeId { get; set; }
        public Nullable<System.DateTime> PromisedDate { get; set; }
        public Nullable<long> PaymentTermsId { get; set; }
        public string PaymentTermsDetail { get; set; }
        public bool BankGuaranteeRequired { get; set; }
        public bool WorkOrderRequired { get; set; }
        public string CommissionType { get; set; }
        public decimal CommissionValue { get; set; }
        public decimal Commission1Value { get; set; }
        public decimal Commission2Value { get; set; }
        public decimal CommissionAmount { get; set; }
        public decimal Commission1Amount { get; set; }
        public decimal Commission2Amount { get; set; }
        public string CommissionTakenBy { get; set; }
        public string CommissionTakerAddress { get; set; }
        public string CommissionContactPerson { get; set; }
        public string CommissionContactNo { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public bool IsSalesDone { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Configuration_PaymentMode Configuration_PaymentMode { get; set; }
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Customer Setup_Customer { get; set; }
        public virtual Setup_Customer Setup_Customer1 { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_TermsAndConditions Setup_TermsAndConditions { get; set; }
        public virtual Setup_TermsAndConditions Setup_TermsAndConditions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesQuotation_Charge> Task_SalesQuotation_Charge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesQuotation_GovtDutyAdjustment> Task_SalesQuotation_GovtDutyAdjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesQuotation_Header> Task_SalesQuotation_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesQuotation_SecurityAndBanking> Task_SalesQuotation_SecurityAndBanking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesQuotation_DeliveryInfo> Task_SalesQuotation_DeliveryInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesQuotationDetail> Task_SalesQuotationDetail { get; set; }
    }
}
