//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_LIMStockIn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_LIMStockIn()
        {
            this.Task_ImportedStockIn = new HashSet<Task_ImportedStockIn>();
            this.Task_LIMStockInDetail = new HashSet<Task_LIMStockInDetail>();
        }
    
        public System.Guid StockInId { get; set; }
        public string StockInNo { get; set; }
        public System.DateTime StockInDate { get; set; }
        public string LIMAgainst { get; set; }
        public System.Guid ProformaInvoiceId { get; set; }
        public string PartShipmentNo { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public string Remarks { get; set; }
        public decimal StockInAmount { get; set; }
        public decimal StockIn1Amount { get; set; }
        public decimal StockIn2Amount { get; set; }
        public bool IsSettledByImportIn { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ImportedStockIn> Task_ImportedStockIn { get; set; }
        public virtual Task_ProformaInvoice Task_ProformaInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_LIMStockInDetail> Task_LIMStockInDetail { get; set; }
    }
}
