//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_Payment()
        {
            this.Task_Payment_GovtDutyAdjustment = new HashSet<Task_Payment_GovtDutyAdjustment>();
            this.Task_PaymentDetail = new HashSet<Task_PaymentDetail>();
            this.Task_PaymentMapping = new HashSet<Task_PaymentMapping>();
        }
    
        public System.Guid PaymentId { get; set; }
        public string PaymentNo { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentAgainst { get; set; }
        public long SupplierId { get; set; }
        public long PaidBy { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal PaidAmount1 { get; set; }
        public decimal PaidAmount2 { get; set; }
        public decimal SecurityDeposit { get; set; }
        public decimal SecurityDeposit1 { get; set; }
        public decimal SecurityDeposit2 { get; set; }
        public Nullable<System.DateTime> RecoveryDate { get; set; }
        public decimal OthersAdjustment { get; set; }
        public decimal OthersAdjustment1 { get; set; }
        public decimal OthersAdjustment2 { get; set; }
        public string ReferenceNo { get; set; }
        public string Remarks { get; set; }
        public long OperationTypeId { get; set; }
        public long OperationalEventId { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public Nullable<System.Guid> VoucherId { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<long> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        public virtual Configuration_OperationalEvent Configuration_OperationalEvent { get; set; }
        public virtual Configuration_OperationType Configuration_OperationType { get; set; }
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Security_User Security_User2 { get; set; }
        public virtual Security_User Security_User3 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_Supplier Setup_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_Payment_GovtDutyAdjustment> Task_Payment_GovtDutyAdjustment { get; set; }
        public virtual Task_Voucher Task_Voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PaymentDetail> Task_PaymentDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PaymentMapping> Task_PaymentMapping { get; set; }
    }
}
