//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_ComplainReceive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_ComplainReceive()
        {
            this.Task_ComplainReceive_Charge = new HashSet<Task_ComplainReceive_Charge>();
            this.Task_ComplainReceiveDetail = new HashSet<Task_ComplainReceiveDetail>();
            this.Task_CustomerDeliveryDetail = new HashSet<Task_CustomerDeliveryDetail>();
            this.Task_ReplacementClaimDetail = new HashSet<Task_ReplacementClaimDetail>();
        }
    
        public System.Guid ReceiveId { get; set; }
        public string ReceiveNo { get; set; }
        public System.DateTime ReceiveDate { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public bool AgainstPreviousSales { get; set; }
        public long CustomerId { get; set; }
        public Nullable<long> RequestedBy { get; set; }
        public decimal TotalChargeAmount { get; set; }
        public decimal TotalCharge1Amount { get; set; }
        public decimal TotalCharge2Amount { get; set; }
        public string Remarks { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Customer Setup_Customer { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ComplainReceive_Charge> Task_ComplainReceive_Charge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ComplainReceiveDetail> Task_ComplainReceiveDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_CustomerDeliveryDetail> Task_CustomerDeliveryDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReplacementClaimDetail> Task_ReplacementClaimDetail { get; set; }
    }
}
