//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_PurchaseOrder()
        {
            this.Task_GoodsReceive = new HashSet<Task_GoodsReceive>();
            this.Task_PaymentMapping = new HashSet<Task_PaymentMapping>();
            this.Task_ProformaInvoiceDetail = new HashSet<Task_ProformaInvoiceDetail>();
            this.Task_PurchaseOrderDetail = new HashSet<Task_PurchaseOrderDetail>();
        }
    
        public System.Guid OrderId { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string PurchaseType { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public long SupplierId { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public long PaymentModeId { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> TermsAndConditionsId { get; set; }
        public string TermsAndConditionsDetail { get; set; }
        public Nullable<long> PaymentTermsId { get; set; }
        public string PaymentTermsDetail { get; set; }
        public string ShipmentType { get; set; }
        public string DeliveryTo { get; set; }
        public string DeliveryContactNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public bool IsSettledByGoodsReceive { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public decimal OrderAmount { get; set; }
        public decimal Order1Amount { get; set; }
        public decimal Order2Amount { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal Paid1Amount { get; set; }
        public decimal Paid2Amount { get; set; }
        public string DiscountType { get; set; }
        public decimal DiscountValue { get; set; }
        public decimal Discount1Value { get; set; }
        public decimal Discount2Value { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal Discount1Amount { get; set; }
        public decimal Discount2Amount { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Configuration_PaymentMode Configuration_PaymentMode { get; set; }
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_Supplier Setup_Supplier { get; set; }
        public virtual Setup_TermsAndConditions Setup_TermsAndConditions { get; set; }
        public virtual Setup_TermsAndConditions Setup_TermsAndConditions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_GoodsReceive> Task_GoodsReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PaymentMapping> Task_PaymentMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ProformaInvoiceDetail> Task_ProformaInvoiceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PurchaseOrderDetail> Task_PurchaseOrderDetail { get; set; }
    }
}
