//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_ReceiveFinalizeDetailSerial
    {
        public System.Guid FinalizeDetailSerialId { get; set; }
        public System.Guid FinalizeDetailId { get; set; }
        public string Serial { get; set; }
        public string AdditionalSerial { get; set; }
    
        public virtual Task_ReceiveFinalizeDetail Task_ReceiveFinalizeDetail { get; set; }
    }
}
