//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_SalesOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_SalesOrder()
        {
            this.Task_CollectionMapping = new HashSet<Task_CollectionMapping>();
            this.Task_DeliveryChallan = new HashSet<Task_DeliveryChallan>();
            this.Task_SalesOrder_Charge = new HashSet<Task_SalesOrder_Charge>();
            this.Task_SalesOrderDeliveryInfo = new HashSet<Task_SalesOrderDeliveryInfo>();
            this.Task_SalesOrderDetail = new HashSet<Task_SalesOrderDetail>();
        }
    
        public System.Guid SalesOrderId { get; set; }
        public string SalesOrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public long CustomerId { get; set; }
        public string CustomerDetail { get; set; }
        public Nullable<long> BuyerId { get; set; }
        public long SalesPersonId { get; set; }
        public string SalesType { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public long OperationTypeId { get; set; }
        public Nullable<long> TermsAndConditionsId { get; set; }
        public string TermsAndConditionsDetail { get; set; }
        public string Remarks { get; set; }
        public string ShipmentType { get; set; }
        public Nullable<System.DateTime> ApxShipmentDate { get; set; }
        public string ShipmentMode { get; set; }
        public long DeliveryFromId { get; set; }
        public Nullable<long> WareHouseId { get; set; }
        public long PaymentModeId { get; set; }
        public Nullable<System.DateTime> PromisedDate { get; set; }
        public Nullable<long> PaymentTermsId { get; set; }
        public string PaymentTermsDetail { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public decimal OrderAmount { get; set; }
        public decimal Order1Amount { get; set; }
        public decimal Order2Amount { get; set; }
        public decimal OrderDiscount { get; set; }
        public decimal Order1Discount { get; set; }
        public decimal Order2Discount { get; set; }
        public decimal GovtDutyAmount { get; set; }
        public decimal GovtDuty1Amount { get; set; }
        public decimal GovtDuty2Amount { get; set; }
        public decimal TotalChargeAmount { get; set; }
        public decimal TotalChargeAmount1 { get; set; }
        public decimal TotalChargeAmount2 { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public decimal CollectedAmount { get; set; }
        public decimal Collected1Amount { get; set; }
        public decimal Collected2Amount { get; set; }
        public string TransactionFrom { get; set; }
        public bool IsSalesModeCash { get; set; }
        public bool IsSettledByChallan { get; set; }
        public string GovtDutyChallanNo { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<long> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        public virtual Configuration_OperationType Configuration_OperationType { get; set; }
        public virtual Configuration_PaymentMode Configuration_PaymentMode { get; set; }
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Security_User Security_User2 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Customer Setup_Customer { get; set; }
        public virtual Setup_Customer Setup_Customer1 { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_Location Setup_Location1 { get; set; }
        public virtual Setup_Location Setup_Location2 { get; set; }
        public virtual Setup_TermsAndConditions Setup_TermsAndConditions { get; set; }
        public virtual Setup_TermsAndConditions Setup_TermsAndConditions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_CollectionMapping> Task_CollectionMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_DeliveryChallan> Task_DeliveryChallan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesOrder_Charge> Task_SalesOrder_Charge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesOrderDeliveryInfo> Task_SalesOrderDeliveryInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesOrderDetail> Task_SalesOrderDetail { get; set; }
    }
}
