//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_ReceiveFinalize
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_ReceiveFinalize()
        {
            this.Task_PaymentMapping = new HashSet<Task_PaymentMapping>();
            this.Task_ReceiveFinalizeDetail = new HashSet<Task_ReceiveFinalizeDetail>();
        }
    
        public System.Guid FinalizeId { get; set; }
        public string FinalizeNo { get; set; }
        public System.DateTime FinalizeDate { get; set; }
        public long SupplierId { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public decimal FinalizeAmount { get; set; }
        public decimal Finalize1Amount { get; set; }
        public decimal Finalize2Amount { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public bool IsSettledByPayment { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal Paid1Amount { get; set; }
        public decimal Paid2Amount { get; set; }
        public string PurchaseOperationType { get; set; }
        public Nullable<long> TermsAndConditionsId { get; set; }
        public string TermsAndConditionsDetail { get; set; }
        public Nullable<long> PaymentTermsId { get; set; }
        public string PaymentTermsDetail { get; set; }
        public string DiscountType { get; set; }
        public decimal DiscountValue { get; set; }
        public decimal Discount1Value { get; set; }
        public decimal Discount2Value { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal Discount1Amount { get; set; }
        public decimal Discount2Amount { get; set; }
        public Nullable<System.Guid> VoucherId { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_Supplier Setup_Supplier { get; set; }
        public virtual Setup_TermsAndConditions Setup_TermsAndConditions { get; set; }
        public virtual Setup_TermsAndConditions Setup_TermsAndConditions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_PaymentMapping> Task_PaymentMapping { get; set; }
        public virtual Task_Voucher Task_Voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReceiveFinalizeDetail> Task_ReceiveFinalizeDetail { get; set; }
    }
}
