//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_LCOpening
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_LCOpening()
        {
            this.Task_ImportCosting = new HashSet<Task_ImportCosting>();
            this.Task_ImportDocuments = new HashSet<Task_ImportDocuments>();
        }
    
        public System.Guid LCId { get; set; }
        public string LCNo { get; set; }
        public System.DateTime LCDate { get; set; }
        public System.Guid ProformaInvoiceId { get; set; }
        public long ImporterBankId { get; set; }
        public long SupplierBankId { get; set; }
        public long SupplierId { get; set; }
        public Nullable<long> LCSupplierId { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public decimal LCAmount { get; set; }
        public decimal LCAmount1 { get; set; }
        public decimal LCAmount2 { get; set; }
        public decimal LCMargin { get; set; }
        public decimal LCMarginAmount { get; set; }
        public decimal LCMarginAmount1 { get; set; }
        public decimal LCMarginAmount2 { get; set; }
        public decimal LTRAmount { get; set; }
        public decimal LTRAmount1 { get; set; }
        public decimal LTRAmount2 { get; set; }
        public string LTRNo { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public bool IsSettledByImportCosting { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Setup_Bank Setup_Bank { get; set; }
        public virtual Setup_Bank Setup_Bank1 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_Supplier Setup_Supplier { get; set; }
        public virtual Setup_Supplier Setup_Supplier1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ImportCosting> Task_ImportCosting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ImportDocuments> Task_ImportDocuments { get; set; }
        public virtual Task_ProformaInvoice Task_ProformaInvoice { get; set; }
    }
}
