//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_SalesReturn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_SalesReturn()
        {
            this.Task_SalesReturnDetail = new HashSet<Task_SalesReturnDetail>();
        }
    
        public System.Guid ReturnId { get; set; }
        public string ReturnNo { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public bool AgainstPreviousSales { get; set; }
        public long CustomerId { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public decimal ReturnAmount { get; set; }
        public decimal Return1Amount { get; set; }
        public decimal Return2Amount { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public string Remarks { get; set; }
        public string Reason { get; set; }
        public Nullable<System.Guid> VoucherId { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Customer Setup_Customer { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Task_Voucher Task_Voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesReturnDetail> Task_SalesReturnDetail { get; set; }
    }
}
