//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_ChequeInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_ChequeInfo()
        {
            this.Task_ChequeTreatment = new HashSet<Task_ChequeTreatment>();
        }
    
        public System.Guid ChequeInfoId { get; set; }
        public Nullable<System.Guid> CollectionDetailId { get; set; }
        public Nullable<System.Guid> EntryVoucherId { get; set; }
        public long BankId { get; set; }
        public string ChequeNo { get; set; }
        public System.DateTime ChequeDate { get; set; }
        public decimal Amount { get; set; }
        public decimal Amount1 { get; set; }
        public decimal Amount2 { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<System.Guid> PaymentDetailId { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Setup_Bank Setup_Bank { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Task_CollectionDetail Task_CollectionDetail { get; set; }
        public virtual Task_PaymentDetail Task_PaymentDetail { get; set; }
        public virtual Task_Voucher Task_Voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ChequeTreatment> Task_ChequeTreatment { get; set; }
    }
}
