//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_CollectionDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_CollectionDetail()
        {
            this.Task_ChequeInfo = new HashSet<Task_ChequeInfo>();
        }
    
        public System.Guid CollectionDetailId { get; set; }
        public System.Guid CollectionId { get; set; }
        public long PaymentModeId { get; set; }
        public decimal Amount { get; set; }
        public decimal Amount1 { get; set; }
        public decimal Amount2 { get; set; }
        public Nullable<System.Guid> VoucherId { get; set; }
    
        public virtual Configuration_PaymentMode Configuration_PaymentMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ChequeInfo> Task_ChequeInfo { get; set; }
        public virtual Task_Collection Task_Collection { get; set; }
        public virtual Task_Voucher Task_Voucher { get; set; }
    }
}
