//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_PostedVoucher
    {
        public System.Guid PostedVoucherId { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid VoucherDetailId { get; set; }
        public string VoucherType { get; set; }
        public long AccountsId { get; set; }
        public long ProjectId { get; set; }
        public decimal Amount { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency1Amount { get; set; }
        public decimal Currency2Rate { get; set; }
        public decimal Currency2Amount { get; set; }
        public Nullable<long> OperationalEventId { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Configuration_OperationalEvent Configuration_OperationalEvent { get; set; }
        public virtual Security_User Security_User { get; set; }
        public virtual Setup_Accounts Setup_Accounts { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_Project Setup_Project { get; set; }
        public virtual Task_VoucherDetail Task_VoucherDetail { get; set; }
    }
}
