//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_SalesInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_SalesInvoice()
        {
            this.Task_CollectionMapping = new HashSet<Task_CollectionMapping>();
            this.Task_ComplainReceiveDetail = new HashSet<Task_ComplainReceiveDetail>();
            this.Task_SalesInvoice_Charge = new HashSet<Task_SalesInvoice_Charge>();
            this.Task_SalesInvoiceDetail = new HashSet<Task_SalesInvoiceDetail>();
            this.Task_SalesReturnDetail = new HashSet<Task_SalesReturnDetail>();
        }
    
        public System.Guid InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public long CustomerId { get; set; }
        public string CustomerDetail { get; set; }
        public Nullable<long> BuyerId { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public string InvoiceDiscountType { get; set; }
        public decimal InvoiceDiscountValue { get; set; }
        public decimal InvoiceDiscount1Value { get; set; }
        public decimal InvoiceDiscount2Value { get; set; }
        public decimal InvoiceDiscount { get; set; }
        public decimal Invoice1Discount { get; set; }
        public decimal Invoice2Discount { get; set; }
        public decimal InvoiceAmount { get; set; }
        public decimal Invoice1Amount { get; set; }
        public decimal Invoice2Amount { get; set; }
        public string CommissionType { get; set; }
        public decimal CommissionValue { get; set; }
        public decimal Commission1Value { get; set; }
        public decimal Commission2Value { get; set; }
        public decimal CommissionAmount { get; set; }
        public decimal Commission1Amount { get; set; }
        public decimal Commission2Amount { get; set; }
        public decimal GovtDutyAmount { get; set; }
        public decimal GovtDuty1Amount { get; set; }
        public decimal GovtDuty2Amount { get; set; }
        public decimal TotalChargeAmount { get; set; }
        public decimal TotalChargeAmount1 { get; set; }
        public decimal TotalChargeAmount2 { get; set; }
        public bool IsSettledByCollection { get; set; }
        public decimal CollectedAmount { get; set; }
        public decimal Collected1Amount { get; set; }
        public decimal Collected2Amount { get; set; }
        public bool IsFullPaid { get; set; }
        public decimal ApprovedCollectedAmount { get; set; }
        public decimal ApprovedCollected1Amount { get; set; }
        public decimal ApprovedCollected2Amount { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public string InvoiceOperationType { get; set; }
        public Nullable<long> TermsAndConditionsId { get; set; }
        public string TermsAndConditionsDetail { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public string Remarks { get; set; }
        public string TransactionFrom { get; set; }
        public bool IsSalesModeCash { get; set; }
        public bool IsSettledByReturn { get; set; }
        public Nullable<System.Guid> VoucherId { get; set; }
        public string GovtDutyChallanNo { get; set; }
        public string DeliveryPlace { get; set; }
        public Nullable<long> TransportTypeId { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<long> EditedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Security_User Security_User2 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Customer Setup_Customer { get; set; }
        public virtual Setup_Customer Setup_Customer1 { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_TermsAndConditions Setup_TermsAndConditions { get; set; }
        public virtual Setup_TransportType Setup_TransportType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_CollectionMapping> Task_CollectionMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ComplainReceiveDetail> Task_ComplainReceiveDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesInvoice_Charge> Task_SalesInvoice_Charge { get; set; }
        public virtual Task_Voucher Task_Voucher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesInvoiceDetail> Task_SalesInvoiceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesReturnDetail> Task_SalesReturnDetail { get; set; }
    }
}
