//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_ItemRequisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_ItemRequisition()
        {
            this.Task_ItemRequisitionDetail = new HashSet<Task_ItemRequisitionDetail>();
            this.Task_RequisitionFinalizeDetail = new HashSet<Task_RequisitionFinalizeDetail>();
            this.Task_TransferRequisitionFinalizeDetail = new HashSet<Task_TransferRequisitionFinalizeDetail>();
        }
    
        public System.Guid RequisitionId { get; set; }
        public string RequisitionNo { get; set; }
        public System.DateTime RequisitionDate { get; set; }
        public long RequestedBy { get; set; }
        public string Remarks { get; set; }
        public bool IsSettled { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ItemRequisitionDetail> Task_ItemRequisitionDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_RequisitionFinalizeDetail> Task_RequisitionFinalizeDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_TransferRequisitionFinalizeDetail> Task_TransferRequisitionFinalizeDetail { get; set; }
    }
}
