//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_ChequeTreatment
    {
        public System.Guid TreatmentId { get; set; }
        public System.Guid ChequeInfoId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public long TreatmentBankId { get; set; }
        public Nullable<System.Guid> VoucherId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Setup_Bank Setup_Bank { get; set; }
        public virtual Task_ChequeInfo Task_ChequeInfo { get; set; }
        public virtual Task_Voucher Task_Voucher { get; set; }
    }
}
