//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_ProformaInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_ProformaInvoice()
        {
            this.Task_LCOpening = new HashSet<Task_LCOpening>();
            this.Task_LIMStockIn = new HashSet<Task_LIMStockIn>();
            this.Task_ProformaInvoiceDetail = new HashSet<Task_ProformaInvoiceDetail>();
        }
    
        public System.Guid InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public long SupplierId { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public byte AmendmentNo { get; set; }
        public string ShipmentMode { get; set; }
        public string Incoterms { get; set; }
        public string ReferenceNo { get; set; }
        public long OperationTypeId { get; set; }
        public long PortOfLoadingId { get; set; }
        public long PortOfDischargeId { get; set; }
        public decimal InvoiceAmount { get; set; }
        public decimal Invoice1Amount { get; set; }
        public decimal Invoice2Amount { get; set; }
        public Nullable<long> TermsAndConditionsId { get; set; }
        public string TermsAndConditionsDetail { get; set; }
        public bool IsSettledByLCOpening { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Configuration_OperationType Configuration_OperationType { get; set; }
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_Port Setup_Port { get; set; }
        public virtual Setup_Port Setup_Port1 { get; set; }
        public virtual Setup_Supplier Setup_Supplier { get; set; }
        public virtual Setup_TermsAndConditions Setup_TermsAndConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_LCOpening> Task_LCOpening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_LIMStockIn> Task_LIMStockIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ProformaInvoiceDetail> Task_ProformaInvoiceDetail { get; set; }
    }
}
