//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_ReplacementClaimDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_ReplacementClaimDetail()
        {
            this.Task_ReplacementClaimDetail_Problem = new HashSet<Task_ReplacementClaimDetail_Problem>();
        }
    
        public System.Guid ClaimDetailId { get; set; }
        public System.Guid ClaimId { get; set; }
        public Nullable<System.Guid> ComplainReceiveId { get; set; }
        public long ProductId { get; set; }
        public Nullable<long> ProductDimensionId { get; set; }
        public long UnitTypeId { get; set; }
        public string Serial { get; set; }
        public string AdditionalSerial { get; set; }
        public string ReceivedSerialNo { get; set; }
        public string ReceivedAdditionalSerial { get; set; }
        public bool IsSettled { get; set; }
        public string StockInBy { get; set; }
        public string StockInRefNo { get; set; }
        public Nullable<System.DateTime> StockInRefDate { get; set; }
        public string LCOrReferenceNo { get; set; }
        public Nullable<System.DateTime> LCOrReferenceDate { get; set; }
        public string ProformaInvoiceNo { get; set; }
        public Nullable<System.DateTime> ProformaInvoiceDate { get; set; }
        public decimal Cost { get; set; }
        public decimal Cost1 { get; set; }
        public decimal Cost2 { get; set; }
    
        public virtual Setup_Product Setup_Product { get; set; }
        public virtual Setup_ProductDimension Setup_ProductDimension { get; set; }
        public virtual Setup_UnitType Setup_UnitType { get; set; }
        public virtual Task_ComplainReceive Task_ComplainReceive { get; set; }
        public virtual Task_ReplacementClaim Task_ReplacementClaim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ReplacementClaimDetail_Problem> Task_ReplacementClaimDetail_Problem { get; set; }
    }
}
