//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_SalesInvoiceDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_SalesInvoiceDetail()
        {
            this.Task_SalesInvoiceDetail_GovtDuty = new HashSet<Task_SalesInvoiceDetail_GovtDuty>();
            this.Task_SalesInvoiceDetailSerial = new HashSet<Task_SalesInvoiceDetailSerial>();
        }
    
        public System.Guid InvoiceDetailId { get; set; }
        public System.Guid InvoiceId { get; set; }
        public System.Guid ChallanId { get; set; }
        public System.Guid ChallanDetailId { get; set; }
        public long ProductEntrySequence { get; set; }
        public long ProductId { get; set; }
        public Nullable<long> ProductDimensionId { get; set; }
        public long UnitTypeId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal Price1 { get; set; }
        public decimal Price2 { get; set; }
        public string DiscountType { get; set; }
        public decimal DiscountValue { get; set; }
        public decimal Discount1Value { get; set; }
        public decimal Discount2Value { get; set; }
        public decimal Discount { get; set; }
        public decimal Discount1 { get; set; }
        public decimal Discount2 { get; set; }
        public decimal InvoiceDiscount { get; set; }
        public decimal InvoiceDiscount1 { get; set; }
        public decimal InvoiceDiscount2 { get; set; }
        public decimal Cost { get; set; }
        public decimal Cost1 { get; set; }
        public decimal Cost2 { get; set; }
        public long PrimaryUnitTypeId { get; set; }
        public Nullable<long> SecondaryUnitTypeId { get; set; }
        public Nullable<long> TertiaryUnitTypeId { get; set; }
        public decimal SecondaryConversionRatio { get; set; }
        public decimal TertiaryConversionRatio { get; set; }
        public Nullable<long> WareHouseId { get; set; }
        public decimal ReturnedQuantity { get; set; }
        public bool IsIncludingGovtDuty { get; set; }
        public Nullable<System.Guid> GoodsReceiveId { get; set; }
        public Nullable<System.Guid> ImportedStockInId { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public string ShortSpecification { get; set; }
        public bool IsWarrantyAvailable { get; set; }
        public decimal WarrantyDays { get; set; }
        public bool IsServiceWarranty { get; set; }
        public decimal ServiceWarrantyDays { get; set; }
    
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_Product Setup_Product { get; set; }
        public virtual Setup_ProductDimension Setup_ProductDimension { get; set; }
        public virtual Setup_Supplier Setup_Supplier { get; set; }
        public virtual Setup_UnitType Setup_UnitType { get; set; }
        public virtual Setup_UnitType Setup_UnitType1 { get; set; }
        public virtual Setup_UnitType Setup_UnitType2 { get; set; }
        public virtual Setup_UnitType Setup_UnitType3 { get; set; }
        public virtual Task_DeliveryChallan Task_DeliveryChallan { get; set; }
        public virtual Task_DeliveryChallanDetail Task_DeliveryChallanDetail { get; set; }
        public virtual Task_GoodsReceive Task_GoodsReceive { get; set; }
        public virtual Task_ImportedStockIn Task_ImportedStockIn { get; set; }
        public virtual Task_SalesInvoice Task_SalesInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesInvoiceDetail_GovtDuty> Task_SalesInvoiceDetail_GovtDuty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_SalesInvoiceDetailSerial> Task_SalesInvoiceDetailSerial { get; set; }
    }
}
