//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_ImportDocuments
    {
        public System.Guid ImportDocumentId { get; set; }
        public System.Guid LCId { get; set; }
        public long CostingGroupId { get; set; }
        public System.Guid DocumentId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Others_Documents Others_Documents { get; set; }
        public virtual Security_User Security_User { get; set; }
        public virtual Setup_CostingGroup Setup_CostingGroup { get; set; }
        public virtual Task_LCOpening Task_LCOpening { get; set; }
    }
}
