//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_ComplainReceiveDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task_ComplainReceiveDetail()
        {
            this.Task_ComplainReceiveDetail_Problem = new HashSet<Task_ComplainReceiveDetail_Problem>();
            this.Task_ComplainReceiveDetail_SpareProduct = new HashSet<Task_ComplainReceiveDetail_SpareProduct>();
        }
    
        public System.Guid ReceiveDetailId { get; set; }
        public System.Guid ReceiveId { get; set; }
        public Nullable<System.Guid> InvoiceId { get; set; }
        public long ProductId { get; set; }
        public Nullable<long> ProductDimensionId { get; set; }
        public long UnitTypeId { get; set; }
        public string Serial { get; set; }
        public string AdditionalSerial { get; set; }
        public bool IsWarrantyAvailable { get; set; }
        public bool IsServiceWarranty { get; set; }
        public bool IsOnlyService { get; set; }
        public decimal Cost { get; set; }
        public decimal Cost1 { get; set; }
        public decimal Cost2 { get; set; }
        public string Remarks { get; set; }
        public decimal TotalSpareAmount { get; set; }
        public decimal TotalSpareAmount1 { get; set; }
        public decimal TotalSpareAmount2 { get; set; }
        public decimal TotalSpareDiscount { get; set; }
        public decimal TotalSpareDiscount1 { get; set; }
        public decimal TotalSpareDiscount2 { get; set; }
        public decimal TotalServiceAmount { get; set; }
        public decimal TotalServiceAmount1 { get; set; }
        public decimal TotalServiceAmount2 { get; set; }
        public decimal TotalServiceDiscount { get; set; }
        public decimal TotalServiceDiscount1 { get; set; }
        public decimal TotalServiceDiscount2 { get; set; }
    
        public virtual Setup_Product Setup_Product { get; set; }
        public virtual Setup_ProductDimension Setup_ProductDimension { get; set; }
        public virtual Setup_UnitType Setup_UnitType { get; set; }
        public virtual Task_ComplainReceive Task_ComplainReceive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ComplainReceiveDetail_Problem> Task_ComplainReceiveDetail_Problem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task_ComplainReceiveDetail_SpareProduct> Task_ComplainReceiveDetail_SpareProduct { get; set; }
        public virtual Task_SalesInvoice Task_SalesInvoice { get; set; }
    }
}
