//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_ChequeInfo
    {
        public System.Guid ChequeInfoId { get; set; }
        public System.Guid CollectionDetailId { get; set; }
        public long BankId { get; set; }
        public string ChequeNo { get; set; }
        public System.DateTime ChequeDate { get; set; }
        public decimal Amount { get; set; }
        public decimal Amount1 { get; set; }
        public decimal Amount2 { get; set; }
    
        public virtual Setup_Bank Setup_Bank { get; set; }
        public virtual Temp_CollectionDetail Temp_CollectionDetail { get; set; }
    }
}
