//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_SalesInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Temp_SalesInvoice()
        {
            this.Temp_CollectionMapping = new HashSet<Temp_CollectionMapping>();
            this.Temp_SalesInvoice_Charge = new HashSet<Temp_SalesInvoice_Charge>();
            this.Temp_SalesInvoiceDetail = new HashSet<Temp_SalesInvoiceDetail>();
        }
    
        public System.Guid InvoiceId { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public long CustomerId { get; set; }
        public string CustomerDetail { get; set; }
        public Nullable<long> BuyerId { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public string InvoiceDiscountType { get; set; }
        public decimal InvoiceDiscountValue { get; set; }
        public decimal InvoiceDiscount1Value { get; set; }
        public decimal InvoiceDiscount2Value { get; set; }
        public decimal InvoiceDiscount { get; set; }
        public decimal Invoice1Discount { get; set; }
        public decimal Invoice2Discount { get; set; }
        public decimal InvoiceAmount { get; set; }
        public decimal Invoice1Amount { get; set; }
        public decimal Invoice2Amount { get; set; }
        public string CommissionType { get; set; }
        public decimal CommissionValue { get; set; }
        public decimal Commission1Value { get; set; }
        public decimal Commission2Value { get; set; }
        public decimal CommissionAmount { get; set; }
        public decimal Commission1Amount { get; set; }
        public decimal Commission2Amount { get; set; }
        public decimal GovtDutyAmount { get; set; }
        public decimal GovtDuty1Amount { get; set; }
        public decimal GovtDuty2Amount { get; set; }
        public decimal TotalChargeAmount { get; set; }
        public decimal TotalChargeAmount1 { get; set; }
        public decimal TotalChargeAmount2 { get; set; }
        public decimal CollectedAmount { get; set; }
        public decimal Collected1Amount { get; set; }
        public decimal Collected2Amount { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public string InvoiceOperationType { get; set; }
        public Nullable<long> TermsAndConditionsId { get; set; }
        public string TermsAndConditionsDetail { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public string Remarks { get; set; }
        public string TransactionFrom { get; set; }
        public bool IsSalesModeCash { get; set; }
        public bool IsSettledByCollection { get; set; }
        public string GovtDutyChallanNo { get; set; }
        public string DeliveryPlace { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPersonNo { get; set; }
        public Nullable<long> TransportId { get; set; }
        public Nullable<long> TransportTypeId { get; set; }
        public string VehicleNo { get; set; }
        public string DriverName { get; set; }
        public string DriverContactNo { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Customer Setup_Customer { get; set; }
        public virtual Setup_Customer Setup_Customer1 { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        public virtual Setup_TermsAndConditions Setup_TermsAndConditions { get; set; }
        public virtual Setup_Transport Setup_Transport { get; set; }
        public virtual Setup_TransportType Setup_TransportType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_CollectionMapping> Temp_CollectionMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_SalesInvoice_Charge> Temp_SalesInvoice_Charge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_SalesInvoiceDetail> Temp_SalesInvoiceDetail { get; set; }
    }
}
