//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Collection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Temp_Collection()
        {
            this.Temp_CollectionDetail = new HashSet<Temp_CollectionDetail>();
            this.Temp_CollectionMapping = new HashSet<Temp_CollectionMapping>();
        }
    
        public System.Guid CollectionId { get; set; }
        public string CollectionNo { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public string SelectedCurrency { get; set; }
        public decimal Currency1Rate { get; set; }
        public decimal Currency2Rate { get; set; }
        public decimal CollectedAmount { get; set; }
        public decimal CollectedAmount1 { get; set; }
        public decimal CollectedAmount2 { get; set; }
        public long CustomerId { get; set; }
        public long SalesPersonId { get; set; }
        public long CollectedBy { get; set; }
        public string MRNo { get; set; }
        public string Remarks { get; set; }
        public long OperationTypeId { get; set; }
        public long OperationalEventId { get; set; }
        public decimal SecurityDeposit { get; set; }
        public decimal SecurityDeposit1 { get; set; }
        public decimal SecurityDeposit2 { get; set; }
        public Nullable<System.DateTime> RecoveryDate { get; set; }
        public decimal OthersAdjustment { get; set; }
        public decimal OthersAdjustment1 { get; set; }
        public decimal OthersAdjustment2 { get; set; }
        public string Approved { get; set; }
        public Nullable<long> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string CancelReason { get; set; }
        public long LocationId { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
        public System.DateTime EntryDate { get; set; }
    
        public virtual Configuration_OperationalEvent Configuration_OperationalEvent { get; set; }
        public virtual Configuration_OperationType Configuration_OperationType { get; set; }
        public virtual Security_User Security_User { get; set; }
        public virtual Security_User Security_User1 { get; set; }
        public virtual Security_User Security_User2 { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Customer Setup_Customer { get; set; }
        public virtual Setup_Employee Setup_Employee { get; set; }
        public virtual Setup_Location Setup_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_CollectionDetail> Temp_CollectionDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_CollectionMapping> Temp_CollectionMapping { get; set; }
    }
}
