//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory360Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_CustomerSupplierOutstanding
    {
        public System.Guid TempId { get; set; }
        public string ReportFor { get; set; }
        public string Group { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string SalesPerson { get; set; }
        public decimal LedgerEndingBalance { get; set; }
        public decimal ReceivedChequeNotTreatedAmount { get; set; }
        public decimal ReceivedDishonourChequeAmount { get; set; }
        public decimal IssuedChequeNotTreatedAmount { get; set; }
        public decimal IssuedDishonourChequeAmount { get; set; }
        public long CompanyId { get; set; }
        public long EntryBy { get; set; }
    
        public virtual Security_User Security_User { get; set; }
        public virtual Setup_Company Setup_Company { get; set; }
        public virtual Setup_Customer Setup_Customer { get; set; }
        public virtual Setup_Supplier Setup_Supplier { get; set; }
    }
}
